### ISSUE TITLE
Commande dans le script d'installation erronée ?

### ISSUE THREAD

**Issue by VongoSanDi** [aaaaadrien/perso-gnome-extension#13]
Bonjour,

lorsque je lance le script d'installation, cela me copie directement le contenu de perso@aaaaadrien.github.com dans ~/.local/share/gnome-shell/extensions/

Il à fallu que je crée manuellement le dossier ~/.local/share/gnome-shell/extensions/perso@aaaaadrien.github.com, puis j'ai copié les fichiers de l'extension dedans.

Je pense qu'il faudrait modifier le script:
Avant: cp -r ./perso@aaaaadrien.github.com $HOME/.local/share/gnome-shell/extensions/
Après: cp -r ./perso@aaaaadrien.github.com $HOME/.local/share/gnome-shell/extensions/perso@aaaaadrien.github.com

**Comment by Fuzzy2319** [comment]
Bonjour,

Pouvez vous me dire quelle distribution Linux vous utilisez?
car je n'ai personnellement aucun problème avec le script d'installation.

J'utilise personnellement Ubuntu 21.10.

**Comment by VongoSanDi** [comment]
Debian 11

**Comment by Fuzzy2319** [comment]
Merci je vais pouvoir tester de ce pas

**Comment by Fuzzy2319** [comment]
Je viens de tester et j'ai eu le bug néanmoins en désinstallant puis en réexécutant le fichier d'installation, le dossier c'est créé correctement depuis impossible de recréer le bug. Peut tu tester si tu as le même phénomène que moi? @VongoSanDi
